### ISSUE TITLE
replace MongoDB with SQLite

### ISSUE THREAD

**Issue by t-cool** [t-cool/flashcards-for-developers#3]
So far, the app uses MongoDB for its DB.
I'd like to replace the DB parts of MongoDB with SQLite.  This is why we don't have to set up MongoDB for the development stage.
I hope that if we choose the NODE/ENV as development, we can switch DB to SQLite instead of MongoDB.

**Comment by t-cool** [comment]
I made a bounty on Bountysource.
It would be happy if you might help me again.
https://www.bountysource.com/issues/68913745-replace-mongodb-with-sqlite

**Comment by t-cool** [comment]
@dhamaniasad 
I made a bounty of $85 in sum.
Could you help me again?
I'd appreciate your help.

**Comment by sahalsaad** [comment]
Can i give a try ?

**Comment by t-cool** [comment]
@sahalsaad 
Thank you for being interested in this issue.
I'm sorry to say, but I asked @dhamaniasad for this issue before, so I'd like to ask him for this task.

**Comment by dhamaniasad** [comment]
@t-cool I've started working on the issue. However, this will require quite a bit more work as the scope is larger, so could you bump the bounty?

Also,
> I hope that if we choose the NODE/ENV as development, we can switch DB to SQLite instead of MongoDB

If I understood that properly, you mentioned wanting to support both MongoDB and SQLite? Or just SQLite will do? Supporting both at the same time will be much harder.

**Comment by t-cool** [comment]
@dhamaniasad 
If we delete the MongoDB parts and just replace it with SQLite, could you deal with this issue at $85?

**Comment by dhamaniasad** [comment]
We can have a chat and discuss your needs from this application and come up with the optimum solution. You can drop me an email, my address is listed on my profile :)

**Comment by t-cool** [comment]
I updated README.  Can you have a check? 
Okay.  Let's talk on Hangout.

**Comment by t-cool** [comment]
I read your last comment just now. 

> you could simply copy the sqlite file to make backups of your database and running the application would be quite simple.

If we use that method, can we start the app just by `yarn web`?  I guess we don't need `yarn server` and instead we need a script to import the data from mongoDB into SQLite.

**Comment by t-cool** [comment]
@sahalsaad 
Thank you for your advice.  I'll keep it in my mind!

**Comment by t-cool** [comment]
https://www.bountysource.com/issues/68913745-replace-mongodb-with-sqlite
