### ISSUE TITLE
adding user account functionality

### ISSUE THREAD

**Issue by t-cool** [t-cool/flashcards-for-developers#4]
@dhamaniasad 
I'd like to add the login for users.

**Comment by t-cool** [comment]
https://www.bountysource.com/issues/68918849-adding-user-account-functionality

**Comment by gabrielsimoes** [comment]
The functionality is working as it is now.

Steps to make it work:
- Setup mongo and setup `DATABASE_URI` to point to it.
- Setup GitHub API for your app here: https://github.com/settings/developers
- Use the API keys Github gave you to setup `REACT_APP_GITHUB_OAUTH_CLIENT_ID`, `REACT_APP_GITHUB_OAUTH_REDIRECT_URI` and `GITHUB_OAUTH_CLIENT_SECRET`.
- Note that the redirect URI at Github website should be something like `https://example.com`, and `REACT_APP_GITHUB_OAUTH_REDIRECT_URI` should have the path `/auth/github` appended like this: `https://example.com/auth/github`.
- Setup `SESSION_SECRET` to a random string.

You can also edit `src/config/index.js` and `config/index.js`, but it is best if you setup the environment variables.

**Comment by t-cool** [comment]
Hi @gabrielsimoes.
Thank you for telling me the info!
I had a talk with @dhamaniasad  and he's trying to implement another way to implement adding user account without Github account.

**Comment by gabrielsimoes** [comment]
Just a few tips man:

If you wanna do business, I wouldn't do it over BountySource.
1) It gets the open source community confused like me. I don't like doing something for nothing.
2) They charge a 10% fee.

**Comment by t-cool** [comment]
Hi @gabrielsimoes 

Thank you for your advice.  My purpose is to use flashcards-for-developers for my English classes.  But I think that I need to customize the system so that I can use for my classes.  For example, students don't have Github accounts, or some of the their computers don't have Internet connection, etc. 

> If you want only one developer to do it, then make it clear, don't post it on a website like BountySource.

I posted the issue as public at first, and @dhamaniasad advised me to add three functionalities to solve the problems.  That's why I asked @dhamaniasad for three issues.  As you mentioned, I should have used the service such as Freelancers or Upworks or asked him directly.  

Of course, I would not use this system for business.  I'll keep this repository for teachers like me.  I keep this repository as public, which might help someone who wants to use this software for education.

**Comment by nlaz** [comment]
Hi @t-cool, Glad you are making use of our codebase. I would love to hear more about what you are trying to do for your classroom. There might be some simple solutions we can add to the original code that will fix the issues you are facing. I would be happy to chat. Cheers!

**Comment by t-cool** [comment]
Hi @nlaz 
Thank you for your message!  Now @dhamaniasad has been trying hard to solve my issue so that I can use flashcards-for-developers in my school's environment.  
After @dhamaniasad finish making the demo and I release the fund on Bountysource, I'll send you the e-mail again.
