### ISSUE TITLE
creating an interface to make flashcards

### ISSUE THREAD

**Issue by t-cool** [t-cool/flashcards-for-developers#5]
I'd like to add the interface to make flashcards.  

When we make a flashcard, it would be hopeful to be able to load many quizzes at a time.

**Comment by t-cool** [comment]
https://www.bountysource.com/issues/68918888-creating-an-interface-to-make-flashcards

**Comment by t-cool** [comment]
https://www.bountysource.com/issues/68913745-replace-mongodb-with-sqlite

**Comment by gabrielsimoes** [comment]
This functionality is already implemented. The user has to be pro to use it. You can make a user pro by doing this (after implementing user functionality as I described in issue #4):

```
mongo
> use admin (or whatever db you are using)
> db.users.findOneAndUpdate({ username: "SOME_USER" }, { $set: { "user_plan" : "pro_monthly" }})
```

You will have to logout and login again due to cookies.

**Comment by t-cool** [comment]
@gabrielsimoes 
Okay!  I'll keep it in my mind!
